name: fairmock_demo
description: "A new Flutter project."
publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  fair:
    git:
      url: https://github.com/wuba/Fair.git
      ref: release-4.0
      path: fair


  fair_pushy:
    path: /Volumes/huc/fair/FairPushy/sdk



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


  build_runner: ^2.0.0
  fair_compiler: ^2.1.2



dependency_overrides:
  build_runner: 2.3.3
  analyzer: 5.6.0
  dart_style: 2.2.5
  collection: 1.17.0


  fair_version:
    git:
      url: https://github.com/wuba/Fair.git
      ref: release-4.0
      path: flutter_version/flutter_mock





flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fair/


